input {
  file {
    path => "C:/Users/nenad/Desktop/9_semestar/UDD/logstash.log"
    start_position => "beginning"
    sincedb_path => "NUL"

    codec => multiline {
      # Regularni izraz koji traži početak svakog novog loga
      pattern => "^REPORT_INDEXED"

      # Ako linija NE počinje sa gornjim patternom (negacija)
      negate => true

      # Zalepi tu liniju na prethodnu liniju
      what => "previous"
    }
  }
}

filter {
  grok {
    match => {
      "message" => "REPORT_INDEXED SUCCESS organization=%{DATA:organization} city=%{DATA:city} analyst=%{DATA:analyst} malware=%{DATA:malware} classification=%{WORD:classification}"
    }
    if "_grokparsefailure" in [tags] {
    drop { }
  }
  }

  mutate {
    strip => ["organization", "city", "analyst", "malware", "classification"]
    lowercase => ["classification"]
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "forensic_report_logs"
  }
  stdout {
    codec => rubydebug
  }
}